### ISSUE TITLE
EdgesObjectModel3d after conversion

### ISSUE THREAD

**Issue by golftra** [asr-ros/asr_halcon_bridge#2]
Hi,
for me it is not possible to use EdgesObjectModel3d after a conversion from a ROS-Pointcloud to a om3 Halcon Pointcloud.
Errorcode: 9521: Required 2D mapping missing in 3D object model
How can I fix this?
Thanks

**Comment by Tobi2001** [comment]
In the description of the HALCON operator EdgesObjectModel3d it says: "The operator supports edge extraction only from 3D object models that contain a XYZ mapping, such as models that were created with XyzToObjectModel3d". The output models of halcon_bridge don't contain that mapping as they are created from 3D point clouds and not from XYZ-images

**Comment by golftra** [comment]
thanks for the fast reply. Is there a way to use the Edge extraction when converting from ROS or PCL Pointclouds?

**Comment by Tobi2001** [comment]
The edge extraction requires that mapping information for each point in your cloud, so unless you don't have that given in your ROS/PCL application I don't think that will work.

**Comment by golftra** [comment]
ok thanks. Do you know if it is possible to import PointCloud Data from the Intel RealSense D435 directly to Halcon without the workaround with ROS?

**Comment by Tobi2001** [comment]
Doesn't look like Halcon has an interface for that model yet. But if your point cloud comes from a stereo camera you probably should be able to get the data as an xyz-image and then convert that to halcon using the appropriate operator. I would look into the manual of the camera sdk and the Halcon documentation to see how to best convert the data

**Comment by Tobi2001** [comment]
Closing issue due to problem being outside of this package scope
