### ISSUE TITLE
Feature: Transform camera calibration between ROS and HALCON

### ISSUE THREAD

**Issue by bbferka** [asr-ros/asr_halcon_bridge#3]
Hi, 

Very col package. Made my life a lot easier. I was wondering if you have any experience in converting from the Halcon calibration object  (polynomial) to ``senros_msgs/CameraInfo``. I would be willing to contribute to the package with the extra functionality, but I can't seem to be able to find a definitive answer for the correspondence between  the distortion coefficients calculated by Halcon and the ones calculated by OpenCV.

**Comment by Tobi2001** [comment]
Hey,

I haven't done that myself but it looks to be pretty straight-forward from what I'm reading here:
https://www.mvtec.com/doc/halcon/13/en/calibrate_cameras.html
and
https://www.ros.org/reps/rep-0104.html

Basically you have to map K1, K2, K3, P1, P2 to k1, k2, k3, t1, t2 (with the plumb_bob distortion model in the ROS message).

We'd be happy to include the new feature into the repository if you want to implement this.

Best regards

**Comment by bbferka** [comment]
@Tobi2001 Thanks for the quick reply. I think it is not that simple. The OpenCV calibration and Halcon calibration of the same camera on the same images results in very different k and p values (orders of magnitude bigger or smaller). 

Based on this conversation on  [stakcoverflow](https://stackoverflow.com/questions/58606394/halcon-to-opencv-distortion-coefficients-convertion) it is impossible. 

After posting the question here I also received confirmation from the distributor of our Halcon license that the conclusion of the stackoverflow conversation is correct and since the OpenCV and Halcon estimations are exact opposites of each other they are not convertible.  I still find it hard to believe though :cry:

**Comment by Tobi2001** [comment]
Ah, I see the problem. I'll close the issue as there seems to be no real solution for now. Feel free to reopen it again once you found a way to convert the values or have a better solution.
