### ISSUE TITLE
ROS2 version

### ISSUE THREAD

**Issue by airballking** [asr-ros/asr_halcon_bridge#5]
Dear maintainers of asr_halcon_bridge, we are using a [fork of this repository](https://github.com/code-iai/asr_halcon_bridge/), and are now starting to port it for ROS2 Foxy. Are you interested in receiving a pull request back for that?

Also, we have a couple of small fixes for the ROS1 branch that we could cherry-pick and pull request back. Also interested? Unfortunately, one of them breaks API.

**Comment by Tobi2001** [comment]
Hi,
we'd be happy to integrate the ROS2 branch and also the code fixes for the ROS1 one.
Just let me know once the port is ready for a PR and I'll add a separate branch for it.

**Comment by nirwester** [comment]
Hi, at Robotcloud we also made a fork for ros2 galactic https://github.com/nirwester/asr_halcon_bridge/tree/galactic (didn't realize @airballking had a similar one already). We also added an handling for nan points in the cloud (now set to 0). Let me know if you would like a PR.

**Comment by Tobi2001** [comment]
Hi,
sorry for the late reply. I've created a ros2 branch, you can create a PR for the ROS2 changes there.

**Comment by airballking** [comment]
@Tobi2001 Thanks for the feedback. I'll discuss with my colleagues on how to proceed.
